# Generated by Django 2.2.7 on 2019-11-13 17:47

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="URL",
            fields=[
                ("password", models.CharField(max_length=10)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("visit_counter", models.IntegerField(default=0)),
                ("url", models.URLField()),
                (
                    "user",
                    models.ForeignKey(on_delete="cascade", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                ("password", models.CharField(max_length=10)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("visit_counter", models.IntegerField(default=0)),
                ("file", models.FileField(upload_to="uploads/")),
                (
                    "user",
                    models.ForeignKey(on_delete="cascade", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
