# Generated by Django 2.2.7 on 2019-11-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("safesend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file", name="password", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="url", name="password", field=models.CharField(max_length=255),
        ),
    ]
