# Generated by Django 2.2.7 on 2019-11-14 13:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("safesend", "0002_auto_20191114_1246"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete="cascade", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="url",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete="cascade", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
